### ISSUE TITLE
Status update in slave simulator

### ISSUE THREAD

**Issue by stianbauge** [SciFiDryer/ModbusMechanic#5] opened 2021-12-12 09:52 UTC
This is a great software, I've been using it for educational purposes. The slave simulator function is really handy, however as a "standalone" slave simulator I found an issue with Modbus Mechanic. It seems that when running it as a slave simulator towards other Modbus Master (software) the slave simulator GUI does not refresh its status on coils and holding registers when receiving write requests from Master. I'm not sure if this mode of operation is the original intension of this slave simulator, although it would be a great feature to be able to simulate slave devices across a network.

(It's running on Windows 10 and Modbus TCP).

It works fine along with the Modbus Master in Modbus Mechanic, however.

**Comment by SciFiDryer** [comment] 2021-12-12 20:37
Hi and thanks for reporting the issue. Glad to see the software is helping expand knowledge around Modbus.

I think what is happening is that the other master is using write single register and write single coil requests (function codes 5 and 6 respectively). As the function name implies, they allow writing to just a single coil or register. Given data types like float and unsigned int 32 are quite common today (which need multiple registers), most Modbus software uses write multiple coils and write multiple registers. If there is a need to write just one register, the length of the write multiple request is just set to 1. ModbusMechanic does this too.

I originally never expected the write single request to be common enough to implement, but you raise an excellent point for slave device troubleshooting and completeness. If a slave device is sending requests for write single, they shouldn't be invisible to the watch window. If you start ModbusMechanic with the -debug option on command line you can see the raw packets by the way.

I have added the implementation in 7d19db3 and will publish an update (probably 2.1) shortly. My tests of 2.0 agree with yours, I do not see updates in the watch window or the slave simulator. Tests in master now show it is resolved.

**Comment by SciFiDryer** [comment] 2021-12-19 17:45
Closing as I cannot reproduce the issue in 2.1.

**Closed by SciFiDryer** 2021-12-19 17:45 UTC
