### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: 0 >= 0

### ISSUE THREAD

**Issue by fulviosuperga** [SciFiDryer/ModbusMechanic#18] opened 2023-06-07 08:51 UTC
**Describe the bug**
Scanning registers from 40000 to 40001 it shows no result and the logging system traces a java.lang.ArrayIndexOutOfBoundsException: 0 >= 0

**To Reproduce**
1. Go to 'Tools->Registry Scanner'
2. Start register: 40000; End register: 4100
3. Press 'Scan'
4. Pop-up shows the progress
5. At the end nothing happens and the console show an Exception

**Screenshots**
<img width="963" alt="bug" src="https://github.com/SciFiDryer/ModbusMechanic/assets/67332143/d74bedac-4d5a-48d7-b4bd-55aeba396a09">

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.2 LTS Desktop Edition

**Java Runtime Version**
openjdk 11.0.19 2023-04-18 64-bit

**Stack Trace**
```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 0 >= 0
	at java.base/java.util.Vector.elementAt(Vector.java:497)
	at java.desktop/javax.swing.table.DefaultTableColumnModel.getColumn(DefaultTableColumnModel.java:295)
	at java.desktop/javax.swing.plaf.basic.BasicTableHeaderUI.getHeaderHeight(BasicTableHeaderUI.java:756)
	at java.desktop/javax.swing.plaf.basic.BasicTableHeaderUI.createHeaderSize(BasicTableHeaderUI.java:788)
	at java.desktop/javax.swing.plaf.basic.BasicTableHeaderUI.getPreferredSize(BasicTableHeaderUI.java:819)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1680)
	at java.desktop/javax.swing.table.JTableHeader.getPreferredSize(JTableHeader.java:447)
	at java.desktop/javax.swing.ViewportLayout.preferredLayoutSize(ViewportLayout.java:98)
	at java.desktop/java.awt.Container.preferredSize(Container.java:1823)
	at java.desktop/java.awt.Container.getPreferredSize(Container.java:1807)
	at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1682)
	at java.desktop/javax.swing.ScrollPaneLayout.layoutContainer(ScrollPaneLayout.java:728)
	at java.desktop/java.awt.Container.layout(Container.java:1537)
	at java.desktop/java.awt.Container.doLayout(Container.java:1526)
	at java.desktop/java.awt.Container.validateTree(Container.java:1722)
	at java.desktop/java.awt.Container.validate(Container.java:1657)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:745)
	at java.desktop/javax.swing.RepaintManager$3.run(RepaintManager.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:742)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1889)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by SciFiDryer** [comment] 2023-06-08 16:27
I am not able to reproduce this exception. Have you tried starting a slave simulator from ModbusMechanic then scanning the same range on the simulator? I can successfully scan registers 40000-40100 on the ModbusMechanic slave simulator.

**Comment by SciFiDryer** [comment] 2023-06-12 17:37
As of right now, I can not reproduce the issue with the details provided. Please confirm if this is an issue. Without more details I'll close this within 24 hours. This issue can be reopened at a later date if new information arises.

**Closed** 2023-06-13 22:42 UTC

**Comment by fulviosuperga** [comment] 2023-06-14 06:56
I've tried to start the simulator but as port 502 is inside the os' reserved port range (1-1024) I get a:
`com.intelligt.modbus.jlibmodbus.exception.ModbusIOException: java.net.BindException: Permission denied (Bind failed)`


I'm investigating the bug (probably is not properly a bug) and I found that on remote host port 502 was set as UDP.
